core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

]

nineworldsdeep/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
import core.views

urlpatterns = [
    #url(r'^$', core.views.index, name='index'), 
    #url(r'^$', TemplateView.as_view(template_name="bootstrap-index.html")),
    url(r'^$', core.views.index, name='index'),
    url(r'^sandbox/', TemplateView.as_view(template_name="bootstrap-index.html")),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^documents/$', core.views.DocumentListView.as_view(), name='documents'),
    url(r'^documents/(?P<pk>\d+)$', core.views.DocumentDetailView.as_view(), name='document-detail'),
    url(r'^quotes/$', core.views.QuoteListView.as_view(), name='quotes'), 
    url(r'^quotes/(?P<pk>\d+)$', core.views.QuoteDetailView.as_view(), name='quote-detail'), #need to check ownership permissions, etc.
    url(r'^quotes/create/$', core.views.QuoteCreate.as_view(), name='quote-create'),
    url(r'^xml/download/$', core.views.xml_download, name='xml-download'),
    url(r'^xml/upload/$', core.views.xml_upload, name='xml-upload'),
    # url(r'^quotes/create/$', core.views.quote_entry, name='quote-create'),
    url(r'^quotes/(?P<pk>\d+)/update/$', core.views.QuoteUpdate.as_view(), name='quote-update'),
    url(r'^quotes/(?P<pk>\d+)/delete/$', core.views.QuoteDelete.as_view(), name='quote-delete'),
    url(r'^myquotes/$', core.views.QuotesPrivateForUserListView.as_view(), name='my-quotes'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class Fragment(models.Model):
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ("text",)

class Document(models.Model):
    name = models.CharField(max_length=200)
    link = models.TextField() #in case we have very long parameter based urls
    fragments = models.ManyToManyField(Fragment)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('document-detail', args=[str(self.id)])

    class Meta:
        ordering = ("name",)


class SourceType(models.Model):
    name = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)

class Source(models.Model):    
    source_type = models.ForeignKey(SourceType, on_delete=models.PROTECT)
    author = models.TextField(blank=True)
    director = models.TextField(blank=True)
    title = models.TextField(blank=True)
    year = models.TextField(blank=True)
    url = models.TextField(blank=True)
    retrieval_date = models.TextField(blank=True)
    source_tag= models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):        
        if self.title:
            return self.title
        elif self.author:
            return self.author
        elif self.director:
            return self.director
        elif self.year:
            return self.year
        elif self.url:
            return self.url
        else:
            return "error displaying source"

    class Meta:
        ordering = ("title", "author", "director", "year", "url",)

class MediaTag(models.Model):
    tag = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.tag

    class Meta:
        ordering = ("tag",)

class SourceExcerpt(models.Model):
    source = models.ForeignKey(Source, on_delete=models.PROTECT)
    content = models.TextField()
    pages = models.TextField(blank=True)
    begin_time = models.TextField(blank=True)
    end_time = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(MediaTag, through='SourceExcerptTagging')

    def __str__(self):
        return self.content

    class Meta:
        ordering = ("content", "pages", "begin_time", "end_time",)

class SourceExcerptTagging(models.Model):
    excerpt = models.ForeignKey(SourceExcerpt, on_delete=models.CASCADE)
    tag = models.ForeignKey(MediaTag, on_delete=models.CASCADE)
    tagged_at = models.DateTimeField(null=True, blank=True)
    untagged_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        unique_together = ('excerpt', 'tag',)

class Quote(models.Model):
    text = models.TextField()
    source = models.ForeignKey(Source, on_delete=models.PROTECT, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    last_accessed = models.DateTimeField(default=datetime.now)
    public_accessible = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)    
    tags = models.ManyToManyField(MediaTag, through='QuoteTagging')

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('quote-detail', args=[str(self.id)])

    def __str__(self):
        return self.text

    @property
    def is_public(self):
        #just an adaptation of a basic example from the tutorial
        #using properties in templates
        if public_accessible:
            return public_accessible
        else:
            return False

class QuoteTagging(models.Model):
    quote = models.ForeignKey(Quote, on_delete=models.CASCADE)
    tag = models.ForeignKey(MediaTag, on_delete=models.CASCADE)
    tagged_at = models.DateTimeField(null=True, blank=True)
    untagged_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('quote', 'tag',)

core/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
# from .models import Fragment, Document, Quote, QuoteAccessLogEntry
from .models import Fragment, Document, Quote, SourceType, Source, MediaTag, QuoteTagging, SourceExcerpt
from .forms import QuoteForm
from django.contrib.auth.models import User
from django import forms

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
#from django.core.urlresolvers import reverse
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, F
import random
from datetime import datetime
import pytz

from django.contrib.auth.decorators import login_required

import xml.etree.ElementTree as ET


def index(request):
    #return HttpResponse("Nine Worlds Deep")

    # adapting from https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Home_page

    # counts 
    num_frags = Fragment.objects.all().count()
    num_docs = Document.objects.all().count()
    num_quotes = Quote.objects.all().count()
    num_users = User.objects.all().count()

    # number of visits to this view, as counted in the session variable
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
 
    # populate with these quotes if none exist
    if num_quotes < 1:
        #for testing
        q = Quote(text="\"The most merciful thing in the world, I think, is the inability of the human mind to correlate all its contents. We live on a placid island of ignorance in the midst of black seas of infinity, and it was not meant that we should voyage far. The sciences, each straining in its own direction, have hitherto harmed us little; but some day the piecing together of dissociated knowledge will open up such terrifying vistas of reality, and of our frightful position therein, that we shall either go mad from the revelation or flee from the light into the peace and safety of a new dark age.\" -- H.P. Lovecraft", public_accessible=True)
        q.save()
        q = Quote(text="\"Inevitably anyone with an independent mind must become 'one who resists or opposes authority or established conventions': a rebel. If enough people come to agree with, and follow, the Rebel, we now have a Devil. Until, of course, still more people agree. And then, finally, we have --- Greatness.\" -- Aleister Crowley", public_accessible=True)
        q.save()
        q = Quote(text="\"Atavistic resurgence, a primal urge towards union with the Divine by returning to the common source of all, is indicated by the backward symbolism peculiar to all Sabbath ceremonies, as also of many ideas connected with witchcraft, sorcery and magic. Whether it be the symbol of the moon presiding over nocturnal ecstasies; the words of power chanted backwards; the back-to-back dance performed in opposition to the sun's course; the devil's tail - are all instances of reversal and symbolic of Will and Desire turning within and down to subconscious regions, to the remote past, there to surprise the required atavistic energy for purposes of transformation, healing, initiation, construction or destruction.\" -- Kenneth Grant, Hidden Lore: Hermetic Glyphs", public_accessible=True)
        q.save()
    
    #ensure the existence of default source and tag
    source_type, created = SourceType.objects.get_or_create(
        name='UNSPECIFIED',
    )

    Source.objects.get_or_create(
        source_type=source_type,
        author='UNSPECIFIED SOURCE',
    )

    media_tag_needs_tagging, created = MediaTag.objects.get_or_create(
        tag='needs tagging',
    )

    media_tag_empyrean_system_tagged, created = MediaTag.objects.get_or_create(
        tag='empyrean system tagged',
    )


    #these numbers are for testing, increase when working
    num_quotes_to_retrieve = 10
    num_quotes_to_randomize = 5

    if request.user.is_authenticated:

        # grab X quotes, select where public_accessible is true or owner is logged in user
        quote_queryset = Quote.objects.filter(Q(owner=request.user)|Q(public_accessible=True)).order_by("last_accessed")[:num_quotes_to_retrieve]
        pass

    else:

        # grab X publicly accessible quotes, select from most recent by id
        quote_queryset = Quote.objects.filter(public_accessible=True).order_by("last_accessed")[:num_quotes_to_retrieve]

    if len(quote_queryset) > num_quotes_to_randomize:

        # take retrieved quotes and randomize to grab Y quotes and add to variable random_quotes
        quote_list = random.sample(list(quote_queryset), num_quotes_to_randomize)

    else:

        quote_list = quote_queryset

    # just passing a list of what we need from each object, instead of the whole object to the template
    quote_list_simple = []


    for quote in quote_list:
        quote.last_accessed = timezone.now()
        quote.save()
        quote_text = quote.text
        
        if quote.source:
            quote_source_text = str(quote.source)
        else:
            quote_source_text = "[no source found]"



        ######### working on alternative ###
        ####################################
        #
        # old code, that (erroneously) includes untagged tag values, comment this out when code below is working
        quote_tags_values_list = quote.tags.values_list('tag', flat=True)

        
        ####################################
        #
        # new code (comment out above when working)
        quote_tags_values = []

        for quote_tagging in quote.quotetagging_set.all():

            testing = False

            if testing:

                quote_tagged_at = str(quote_tagging.tagged_at)
                quote_untagged_at = str(quote_tagging.untagged_at)
                quote_tag_value = str(quote_tagging.tag.tag)

                output_test = quote_tag_value + "-> tagged: "
                output_test += quote_tagged_at + " untagged: "
                output_test += quote_untagged_at
                quote_tags_values.append(output_test)

            else:

                tagged_at = quote_tagging.tagged_at
                untagged_at = quote_tagging.untagged_at

                if untagged_at is not None:

                    if (tagged_at is not None and
                        tagged_at == max(tagged_at, untagged_at)):

                        quote_tags_values.append(str(quote_tagging.tag.tag))

                else:

                    quote_tags_values.append(str(quote_tagging.tag.tag))


        quote_tags_values_list = quote_tags_values

        #
        #
        ####################################
        ######### end of alternative work ###


        if len(quote_tags_values_list) < 1:
            
            # quote_tagging, quote_tagging_created = QuoteTagging.objects.get_or_create(quote=quote, tag=media_tag_needs_tagging)
            # quote_tagging.tagged_at=timezone.now()
            # quote_tagging.save()

            # quote_tagging, quote_tagging_created = QuoteTagging.objects.get_or_create(quote=quote, tag=media_tag_empyrean_system_tagged)
            # quote_tagging.tagged_at=timezone.now()
            # quote_tagging.save()

            # quote_tags_values_list = quote.tags.values_list('tag', flat=True)      
            pass      

        if len(quote_tags_values_list) > 0:
            quote_tag_string = ", ".join(quote_tags_values_list)
        else:
            quote_tag_string = ""

        quote_list_simple.append((quote_text, quote_source_text, quote_tag_string))
        


    # render
    return render(
        request,
        'index.html',
        context = {
            'num_frags':num_frags, 
            'num_docs':num_docs, 
            'num_quotes':num_quotes,
            'num_visits': num_visits,
            'num_users':num_users,
            'quote_list_simple': quote_list_simple,
        },
    )

# @login_required
# def quote_entry(request):
#     #if its a post request, process the data
#     if(request.method == 'POST'):
        
#         #create form instance and populate with data from the request
#         form = QuoteForm(request.POST)

#         #check form validity
#         if form.is_valid():
#             #proces the data in form.cleaned_data
#             quote = Quote()
#             quote.text = form.cleaned_data['quote_text']
#             quote.public_accessible = form.cleaned_data['public_accessible']
#             quote.owner = request.user
#             quote.save()

#             return HttpResponseRedirect(reverse('my-quotes'))

#     #if this is a GET (or any other method) create the default form
#     else:

#         form = QuoteForm()

#     return render(request, 'core/')

class DocumentListView(generic.ListView):
    model = Document
    paginate_by = 2 #low for testing, increase for production

class DocumentDetailView(generic.DetailView):
    model = Document

class QuoteListView(generic.ListView):
    model = Quote

class QuoteDetailView(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
    model = Quote

    def test_func(self):
        """ Only let the user access this page if they own the quote being updated"""
        return self.get_object().public_accessible or self.get_object().owner == self.request.user 

class QuotesPrivateForUserListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class based view listing quotes added by users
    """
    model = Quote
    template_name = 'core/quote_list_private_for_user.html'
    paginate_by = 20

    def get_queryset(self):
        return Quote.objects.filter(Q(owner=self.request.user)|Q(public_accessible=True)).order_by('-created_at')


class QuoteCreate(CreateView):
    model = Quote
    form_class = QuoteForm

    def form_valid(self, form):

templates/core/document_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ document.title }}</h1>

  <p><strong>Link:</strong> {{ document.link }}</p>
  <p><strong>CreatedAt:</strong> {{ document.created_at }}</p> 
  <p><strong>UpdatedAt:</strong> {{ document.updated_at }}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Fragments</h4>

    {% for fragment in document.fragment_set.all %}
    <hr>
    <p><strong>Text: </strong> {{ fragment.text }}</p>
    <p><strong>CreatedAt: </strong> {{ fragment.created_at }}</p>
    <p><strong>UpdatedAt: </strong> {{ fragment.updated_at }}</p>

    {% endfor %}
  </div>

{% endblock %}

templates/core/document_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Document List</h1>

    {% if document_list %}
    <ul>

      {% for document in document_list %}
      <li>
        <a href="{{ document.get_absolute_url }}">{{ document.name }}</a> ({{document.link}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no documents in nwd.</p>
    {% endif %}       
{% endblock %}

templates/core/quote_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Quote</h1>

<p>Are you sure you want to delete the quote: {{ quote.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

templates/core/quote_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Owner: {{ quote.title }}</h1>

  <p><strong>Text:</strong> {{ quote.text }}</p>
  <p><strong>CreatedAt:</strong> {{ quote.created_at }}</p> 
  <p><strong>UpdatedAt:</strong> {{ quote.updated_at }}</p>  


{% endblock %}

templates/core/quote_form.html
{% extends "base_generic.html" %}

{% block content %}
<div class="text-center">
	<form action="" method="post">
	    {% csrf_token %}
	    
	    {{ form.as_p }}

	    <input class="btn-red" type="submit" value="Submit" />
	    
	</form>
</div>
{% endblock %}

templates/core/quote_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Quote List</h1>

    {% if quote_list %}
    <ul>

      {% for quote in quote_list %}

        {% if quote.public_accessible %}
            <li>
                <a href="{{ quote.get_absolute_url }}">{{ quote.text }}</a> (public)
            </li>
        {% endif %}

      {% endfor %}

    </ul>
    {% else %}
      <p>There are no quotes in nwd.</p>
    {% endif %}       
{% endblock %}

templates/core/quote_list_private_for_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Added quotes</h1>

    <p><a href="{% url 'quote-create' %}">Add Quote</a></p>

    {% if quote_list %}
    <ul>

      {% for quote in quote_list %} 
      <li>
        [Owner: {% if quote.owner %} {{quote.owner}} {% else %} Anonymous {% endif %}]
        {% if not quote.public_accessible %} (private) {% endif %} <br/> <br/>
        {{quote.text}} <br/> <br/>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no private quotes.</p>
    {% endif %}       
{% endblock %}

templates/core/xml_upload.html
{% extends "base_generic.html" %}

{% block content %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="file">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_name %}
    <p>File uploaded: {{ uploaded_file_name }}</p>
  {% endif %}

  {% if xml_upload_processed_message %}
  	<p>Xml Upload Processed: {{ xml_upload_processed_message }}</p>
  {% endif %}

  {% if sources_processed %} 
    <p>Sources Processed: {{ sources_processed }}</p>
  {% endif %}

  {% if source_location_subset_entries_processed %} 
    <p>Source Location Subset Entries Processed: {{ source_location_subset_entries_processed }}</p>
  {% endif %}
  
  {% if source_excerpts_processed %} 
    <p>Source Excerpts Processed: {{ source_excerpts_processed }}</p>
  {% endif %}
  
  {% if source_excerpt_annotations_processed %} 
    <p>Source Excerpt Annotations Processed: {{ source_excerpt_annotations_processed }}</p>
  {% endif %}
  
  {% if tags_processed %} 
    <p>Tags Processed: {{ tags_processed }}</p>
  {% endif %}
  
  {% endblock %}